# Copyright (C) 2019, Khulnasoft Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Khulnasoft authd password secret

apiVersion: v1
kind: Secret
metadata:
  name: khulnasoft-authd-pass
  namespace: khulnasoft
data:
  authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded
