# Copyright (C) 2019, Khulnasoft Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds khulnasoft namespace to all resources.
namespace: khulnasoft

secretGenerator:
  - name: indexer-certs
    files:
      - certs/indexer_cluster/root-ca.pem
      - certs/indexer_cluster/node.pem
      - certs/indexer_cluster/node-key.pem
      - certs/indexer_cluster/dashboard.pem
      - certs/indexer_cluster/dashboard-key.pem
      - certs/indexer_cluster/admin.pem
      - certs/indexer_cluster/admin-key.pem
      - certs/indexer_cluster/filebeat.pem
      - certs/indexer_cluster/filebeat-key.pem
  - name: dashboard-certs
    files:
      - certs/dashboard_http/cert.pem
      - certs/dashboard_http/key.pem
      - certs/indexer_cluster/root-ca.pem

configMapGenerator:
  - name: indexer-conf
    files:
      - indexer_stack/khulnasoft-indexer/indexer_conf/opensearch.yml
      - indexer_stack/khulnasoft-indexer/indexer_conf/internal_users.yml
  - name: khulnasoft-conf
    files:
      - khulnasoft_managers/khulnasoft_conf/master.conf
      - khulnasoft_managers/khulnasoft_conf/worker.conf
  - name: dashboard-conf
    files:
      - indexer_stack/khulnasoft-dashboard/dashboard_conf/opensearch_dashboards.yml

resources:
  - base/khulnasoft-ns.yaml
  - base/storage-class.yaml

  - secrets/khulnasoft-api-cred-secret.yaml
  - secrets/khulnasoft-authd-pass-secret.yaml
  - secrets/khulnasoft-cluster-key-secret.yaml
  - secrets/dashboard-cred-secret.yaml
  - secrets/indexer-cred-secret.yaml

  - khulnasoft_managers/khulnasoft-cluster-svc.yaml
  - khulnasoft_managers/khulnasoft-master-svc.yaml
  - khulnasoft_managers/khulnasoft-workers-svc.yaml
  - khulnasoft_managers/khulnasoft-master-sts.yaml
  - khulnasoft_managers/khulnasoft-worker-sts.yaml

  - indexer_stack/khulnasoft-indexer/indexer-svc.yaml
  - indexer_stack/khulnasoft-indexer/cluster/indexer-api-svc.yaml
  - indexer_stack/khulnasoft-indexer/cluster/indexer-sts.yaml

  - indexer_stack/khulnasoft-dashboard/dashboard-svc.yaml
  - indexer_stack/khulnasoft-dashboard/dashboard-deploy.yaml
