# Copyright (C) 2019, Khulnasoft Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: khulnasoft-manager-master
  namespace: khulnasoft
spec:
  template:
    spec:
      containers:
        - name: khulnasoft-manager
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: khulnasoft-manager-master
        namespace: khulnasoft
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: khulnasoft-storage
        resources:
          requests:
            storage: 50Gi
