# Copyright (C) 2019, Khulnasoft Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../khulnasoft
patches:
- path: storage-class.yaml
- path: indexer-resources.yaml
- path: khulnasoft-resources.yaml
